import { useEffect, useState } from 'react'
import './App.css'
import { advanceIncident, createOpsState, incidents, inspectTool, resolveAction, selectAsset, tick, type OpsState, type ServiceId } from './domain/operationsEngine'

const assets: { id: ServiceId; name: string; sub: string; x: number; y: number }[] = [
  { id: 'edge', name: 'EDGE-01', sub: 'WAF / load balancer', x: 10, y: 48 }, { id: 'api', name: 'API CLUSTER', sub: 'API-01 / API-02', x: 34, y: 27 }, { id: 'payments', name: 'PAYMENTS', sub: 'PAY-01', x: 58, y: 27 }, { id: 'database', name: 'DATABASE', sub: 'DB-01 primary', x: 82, y: 48 }, { id: 'identity', name: 'IDENTITY', sub: 'SSO / MFA', x: 34, y: 73 }, { id: 'endpoints', name: 'ENDPOINTS', sub: 'Finance / staff', x: 65, y: 73 },
]

export default function App() {
  const [state, setState] = useState<OpsState>()
  const [mode, setMode] = useState<OpsState['mode']>('timed')
  useEffect(() => { if (!state || state.mode === 'untimed' || state.incidentStatus !== 'active') return; const timer = window.setInterval(() => { if (!document.hidden) setState((current) => current ? tick(current) : current) }, 1000); return () => window.clearInterval(timer) }, [state])
  if (!state) return <Start mode={mode} setMode={setMode} start={() => setState(createOpsState(mode))} />
  if (state.shiftOutcome !== 'in-progress') return <Summary state={state} replay={() => setState(createOpsState(mode))} />
  if (state.incidentStatus === 'review') return <Review state={state} next={() => setState(advanceIncident(state))} />
  return <Dashboard state={state} setState={setState} />
}

function Brand() { return <div className="brand"><span className="brand-mark">PS</span><span><strong>PHISHSHIELD</strong><small>NORTHSTAR SOC</small></span></div> }
function Start({ mode, setMode, start }: { mode: OpsState['mode']; setMode: (mode: OpsState['mode']) => void; start: () => void }) { return <main className="start-screen"><section><Brand /><p className="kicker">SHIFT 07 / NORTHSTAR COMMERCE</p><h1>Keep the company<br /><span>secure and online.</span></h1><p className="start-copy">Operate a live company environment. Correlate alerts, infrastructure, and business signals. Respond without turning normal activity into an incident.</p><div className="mode-picker" role="radiogroup" aria-label="Shift timing"><button className={mode === 'timed' ? 'active' : ''} role="radio" aria-checked={mode === 'timed'} onClick={() => setMode('timed')}>Live / timed</button><button className={mode === 'untimed' ? 'active' : ''} role="radio" aria-checked={mode === 'untimed'} onClick={() => setMode('untimed')}>Training / untimed</button></div><button className="launch" onClick={start}>Start live shift <span>→</span></button><p className="fine-print">Fictional systems. Local-only session. No live links or credentials.</p></section><aside className="start-status"><p>PRE-FLIGHT STATUS</p>{['Edge network ready','Application telemetry online','Identity signals connected','Endpoint sensors online'].map((item) => <div key={item}><span>●</span>{item}<b>OK</b></div>)}<dl><div><dt>Incidents</dt><dd>03</dd></div><div><dt>Health</dt><dd>100%</dd></div><div><dt>Role</dt><dd>SOC + DEVOPS</dd></div></dl></aside></main> }

function Dashboard({ state, setState }: { state: OpsState; setState: (state: OpsState) => void }) {
  const incident = incidents[state.incidentIndex]
  return <div className="ops-shell"><Header state={state} /><main className="dashboard">
    <section className="topology panel"><PanelHead eyebrow="LIVE INFRASTRUCTURE" title="Company network" meta="6 ASSETS / 1 AFFECTED" /><div className="map" role="group" aria-label="Company infrastructure map"><svg viewBox="0 0 100 100"><path d="M14 48 L34 27 L58 27 L82 48 M14 48 L34 73 L65 73 L82 48 M34 27 L34 73 M58 27 L65 73" /></svg>{assets.map((asset) => { const affected = asset.id === incident.affectedAsset; return <button key={asset.id} style={{ left: `${asset.x}%`, top: `${asset.y}%` }} className={`node ${affected ? 'affected' : ''} ${state.selectedAsset === asset.id ? 'selected' : ''}`} aria-label={`${asset.name}, ${affected ? 'affected' : 'healthy'}`} onClick={() => setState(selectAsset(state, asset.id))}><i /><strong>{asset.name}</strong><small>{asset.sub}</small><em>{affected ? 'AFFECTED' : 'HEALTHY'}</em></button>})}</div><div className="asset-readout"><span>SELECTED ASSET</span><strong>{assets.find((item) => item.id === state.selectedAsset)?.name}</strong><small>{state.selectedAsset === incident.affectedAsset ? incident.alert : 'Telemetry within baseline'}</small></div></section>
    <section className="alerts panel"><PanelHead eyebrow="ALERT QUEUE" title="Active signals" meta="4 OPEN" /><article className={`alert active ${incident.severity}`}><span>01</span><div><small>{incident.source} / NOW</small><strong>{incident.title}</strong><p>{incident.alert}</p><em>{incident.affectedAsset.toUpperCase()} / ACTIONABLE</em></div></article>{['Certificate expiry / 29 days','Backup completed / DB-01','VPN failures / within baseline'].map((text, i) => <article className="alert noise" key={text}><span>0{i + 2}</span><div><small>MONITOR / {i + 2}M</small><strong>{text}</strong><em>{i === 1 ? 'INFO' : 'LOW'}</em></div></article>)}</section>
    <section className="telemetry panel"><PanelHead eyebrow="LIVE TELEMETRY" title="Correlated signals" meta="30 SEC WINDOW" /><div className="charts">{incident.telemetry.map((series) => <div className="chart" key={series.label}><header><span>{series.label}</span><strong className={series.tone}>{series.value}</strong></header><Spark points={series.points} tone={series.tone} /></div>)}</div></section>
    <section className="investigation panel"><PanelHead eyebrow="INVESTIGATION" title="Evidence sources" meta={`${state.inspectedTools.length}/${incident.tools.length} OPENED`} /><div className="tool-tabs">{incident.tools.map((tool) => <button key={tool.id} className={state.inspectedTools.includes(tool.id) ? 'opened' : ''} onClick={() => setState(inspectTool(state, tool.id))}>{tool.label}<span>{state.inspectedTools.includes(tool.id) ? 'VIEWED' : 'OPEN'}</span></button>)}</div><div className="findings" aria-live="polite">{state.inspectedTools.length === 0 ? <p className="empty">Select a source. Findings are observations, not conclusions.</p> : incident.tools.filter((tool) => state.inspectedTools.includes(tool.id)).map((tool) => <article key={tool.id}><small>{tool.label.toUpperCase()} / {tool.finding.label}</small><strong>{tool.finding.value}</strong><p>{tool.finding.detail}</p></article>)}</div></section>
    <section className="actions panel"><PanelHead eyebrow="RESPONSE" title="Take operational action" meta="RESOLVES INCIDENT" /><div className="action-list">{incident.actions.map((action) => <button key={action.id} onClick={() => setState(resolveAction(state, action.id))}><span><strong>{action.label}</strong><small>{action.consequence}</small></span><b>→</b></button>)}</div></section>
    <section className="stream panel"><PanelHead eyebrow="EVENT STREAM" title="Northstar activity" meta="LIVE" /><ol>{incident.events.map((event, i) => <li key={event}><time>+0{i}:00</time><span className={i >= 2 ? 'warn-dot' : ''} />{event}</li>)}</ol></section>
  </main></div>
}

function Header({ state }: { state: OpsState }) { return <header className="ops-header"><Brand /><div className="shift-live"><i />LIVE SHIFT <span>07 / NORTHSTAR</span></div><div className="health"><small>COMPANY HEALTH</small><strong>{state.companyHealth}%</strong><span><i style={{ width: `${state.companyHealth}%` }} /></span></div><div className="score"><small>SCORE</small><strong>{state.score.toLocaleString()}</strong></div><div className={`countdown ${state.remainingSeconds <= 15 ? 'urgent' : ''}`} role="timer" aria-label={state.mode === 'untimed' ? 'Decision countdown disabled' : `Decision countdown ${state.remainingSeconds} seconds`}><small>DECISION WINDOW</small><strong>{state.mode === 'untimed' ? 'UNTIMED' : `00:${String(state.remainingSeconds).padStart(2, '0')}`}</strong></div></header> }
function PanelHead({ eyebrow, title, meta }: { eyebrow: string; title: string; meta: string }) { return <header className="panel-head"><div><small>{eyebrow}</small><h2>{title}</h2></div><span>{meta}</span></header> }
function Spark({ points, tone }: { points: number[]; tone: string }) { const max = Math.max(...points, 1); return <svg className={`spark ${tone}`} viewBox="0 0 100 42" preserveAspectRatio="none"><path d="M0 39H100" /><polyline points={points.map((point, i) => `${i * 20},${38 - point / max * 32}`).join(' ')} /></svg> }
function Review({ state, next }: { state: OpsState; next: () => void }) { const incident = incidents[state.incidentIndex], result = state.resolvedIncidents.at(-1)!; return <main className="review-screen"><Brand /><section><p className="kicker">INCIDENT 0{state.incidentIndex + 1} / CLOSED</p><div className={`outcome ${result.outcome}`}>{result.outcome.toUpperCase()}</div><h1>{incident.title}</h1><p className="root-cause">ROOT CAUSE <strong>{incident.rootCause.replaceAll('-', ' ')}</strong></p><p className="review-copy">{incident.review}</p><div className="review-grid"><div><small>ACTION</small><strong>{incident.actions.find((item) => item.id === result.action)?.label ?? 'No response'}</strong><p>{result.consequence}</p></div><div><small>COMPANY HEALTH</small><strong>{result.healthDelta > 0 ? '+' : ''}{result.healthDelta}</strong><p>{state.companyHealth}% remaining</p></div><div><small>SCORE</small><strong>{result.scoreDelta > 0 ? '+' : ''}{result.scoreDelta}</strong><p>Evidence bonus +{result.evidenceBonus}</p></div></div><button className="launch" onClick={next}>{state.incidentIndex === 2 ? 'Close shift' : 'Continue shift'} <span>→</span></button></section></main> }
function Summary({ state, replay }: { state: OpsState; replay: () => void }) { return <main className="review-screen summary"><Brand /><section><p className="kicker">SHIFT 07 / COMPLETE</p><h1>Northstar remained <span>operational.</span></h1><p className="review-copy">Three signals, three different causes. Strong operations work separates customer demand, software failure, and malicious activity before acting.</p><div className="review-grid"><div><small>FINAL HEALTH</small><strong>{state.companyHealth}%</strong></div><div><small>FINAL SCORE</small><strong>{state.score.toLocaleString()}</strong></div><div><small>INCIDENTS</small><strong>{state.resolvedIncidents.length}/3</strong></div></div><ol className="shift-results">{state.resolvedIncidents.map((result, i) => <li key={result.incidentId}><span>0{i + 1}</span><strong>{incidents[i].title}</strong><em>{result.outcome}</em></li>)}</ol><button className="launch" onClick={replay}>Replay shift <span>↻</span></button></section></main> }
